# Generated by Django 5.2.3 on 2025-06-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_utilisateur_is_active_utilisateur_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_active',
        ),
    ]
