# Generated by Django 5.2.3 on 2025-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_utilisateur_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='account_image',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profil/'),
        ),
    ]
