# Generated by Django 5.2.3 on 2025-07-27 18:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_utilisateur_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='account_image',
            field=models.ImageField(default=account.models.default_photo_profil, upload_to='photo_profil/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='account_name',
            field=models.CharField(max_length=200, verbose_name='Votre nom et prenoms'),
        ),
    ]
