# Generated by Django 5.2.3 on 2025-07-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_utilisateur_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='account_name',
            field=models.CharField(max_length=200, verbose_name='Votre nom et prenoms'),
        ),
    ]
