# Generated by Django 5.2.3 on 2025-09-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_utilisateur_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='is_active',
        ),
    ]
