# Generated by Django 5.2.3 on 2025-06-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='groupe_tache',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='tache.taskgroup'),
        ),
    ]
