# Generated by Django 5.2.3 on 2025-06-30 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0002_alter_task_groupe_tache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskgroup',
            name='collaborateurs',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='proprietaire',
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=200)),
                ('description_tache', models.TextField(blank=True, null=True)),
                ('status_tache', models.CharField(choices=[('à faire', 'à faire'), ('en cours', 'en cours'), ('termine', 'termine')], default='à faire', max_length=10)),
                ('priorite_tache', models.CharField(choices=[('Basse', 'Basse'), ('Moyenne', 'Moyenne'), ('Haute', 'Haute')], default='Basse', max_length=10)),
                ('echeance_tache', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborateurs', models.ManyToManyField(blank=True, related_name='shared_list', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietaire_liste', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sous_tache', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tache', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='tache.tache')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
