# Generated by Django 5.2.3 on 2025-07-29 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0003_remove_taskgroup_collaborateurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='priorite_tache',
        ),
        migrations.AlterField(
            model_name='tache',
            name='echeance_tache',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
